[package]
name = "cue-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ebnf = "0.1.2"
pest = "2.1.3"
pest_derive = "2.1.0"
